id: PB781F333
initial_creation_type: ocr
source_metadata:
  volumes:
    3aa0fa8fb8d042eca0da009a292fcb11:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: འཕགས་པ་སྤྱན་རས་གཟིགས་དབང་ཕྱུག་ཕྱག་སྟོང་པའི་སྒྲུབ་ཐབས།
      total_pages: 1379
      volume_number: 37
